#!/usr/bin/env bash
#
# PreToolUse hook: refuse edits to files that must never be hand-modified.
#
#   migrations/**  already-applied migrations are generated by `make db-diff`;
#                  editing one desyncs deployed schema from version history
#   .env*.local    real secrets, mirrored by the Read deny rules in ~/.claude
#
# Exit code 2 blocks the tool call and feeds stderr back as the reason.
#
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

file=$(jq -r '.tool_input.file_path // empty' 2>/dev/null)
[ -n "$file" ] || exit 0

case "$file" in
    "$root"/*) rel="${file#"$root"/}" ;;
    *) rel="$file" ;;
esac

case "$rel" in
    migrations/*)
        # creating a brand-new migration file is fine; rewriting an applied one is not
        if [ -e "$file" ]; then
            echo "Refused: $rel is an applied migration." >&2
            echo "Migrations are generated, never edited. Change the entity and run 'make db-diff' to produce a new one." >&2
            exit 2
        fi
        ;;
    .env.local | .env.*.local)
        echo "Refused: $rel holds real credentials and is git-ignored." >&2
        echo "Ask the user to edit it directly, or add the variable to .env with a safe default instead." >&2
        exit 2
        ;;
esac

exit 0
