presta_sitemap:
    defaults:
        priority: 0.5
        changefreq: weekly
        lastmod: now

    alternate:
        enabled: true
        default_locale: '%app.default_locale%'
        locales: '%app.enabled_locales%'
        i18n: symfony

    dump_directory: '%kernel.project_dir%/var/sitemaps'
