twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@TalesFromADevFlowbite/form/default.html.twig'

when@test:
    twig:
        strict_variables: true
