twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'

    globals:
        social_accounts: '%app.social_accounts%'
        enabled_locales: '%app.enabled_locales%'
        default_locale: '%app.default_locale%'

when@test:
    twig:
        strict_variables: true
