when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        faker:
            locale: fr_FR # set the locale
            
        instantiator:
            use_constructor:  true
        
        orm:
            auto_persist: true
            reset:
                connections: [ default ]
                entity_managers: [ default ]
                mode: schema

when@test: *dev
