---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    env_file:
      - .env.local
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  php-worker:
    profiles:
      - donotstart

  php-consumer:
    extends:
      file: compose.yaml
      service: php-worker
    image: ${IMAGES_PREFIX:-}app-php-consumer
    build:
      context: .
      target: frankenphp_prod
    command: [ 'bin/console', 'messenger:consume', '--time-limit=60', '--limit=10', '--memory-limit=128M', '--all' ]
    depends_on:
      php:
        condition: service_healthy
      database:
        condition: service_healthy

###> doctrine/doctrine-bundle ###
  database:
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
