website_controllers:
    resource:
        path: ../src/Ui/Controller/Website
        namespace: App\Ui\Controller\Website
    type: annotation
    name_prefix: app_website_
    prefix:
        fr: ''
        en: '/en'

controllers:
    resource:
        path: ../src/Ui/Controller/
        namespace: App\Ui\Controller
    type: attribute
    
app_website_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template: 'website/home.html.twig'
