# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.contact_email: '%env(CONTACT_EMAIL)%'
    app.contact_phone: '%env(CONTACT_PHONE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $contactEmail: '%app.contact_email%'
            string $contactPhone: '%app.contact_phone%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Model/'
            - '../src/Kernel.php'
    
    Fixtures\:
        resource: '../fixtures/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Doctrine serializer
    serializer_doctrine:
        alias: serializer
        public: true

    # GitHub service
    App\Infrastructure\GitHub\GitHubService:
        arguments:
            $githubUsername: '%env(GITHUB_USERNAME)%'
    
    # Twitter service
    App\Infrastructure\Twitter\TwitterService:
        arguments:
            $twitterUserId: '%env(TWITTER_USER_ID)%'

when@test:
    services:
        app.github:
            alias: App\Infrastructure\GitHub\GitHubService
            public: true

        app.twitter:
            alias: App\Infrastructure\Twitter\TwitterService
            public: true
