<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250614083725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, position VARCHAR(255) NOT NULL, description TEXT DEFAULT \'\' NOT NULL, start_at DATE NOT NULL, end_at DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, average_daily_rate SMALLINT DEFAULT 500 NOT NULL, available BOOLEAN DEFAULT false NOT NULL, available_at DATE DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE settings');
    }
}
