name: cd

on:
  workflow_dispatch:
    
jobs:
  deployment:
    name: Deploy production
    
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd app
            git pull origin main --quiet --rebase
            SERVER_NAME=${{ secrets.SERVER_NAME }} \
            APP_SECRET=${{ secrets.APP_SECRET }} \
            CADDY_MERCURE_JWT_SECRET=${{ secrets.JWT_SECRET }} \
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up --detach --build --force-recreate --no-deps
