name: cd

run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        type: environment
        required: true
      
      tag:
        description: 'Tag to deploy'
        type: string
        required: true

jobs:
  deployment:
    name: Deploy ${{ inputs.environment }}
    
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to droplet
        run: >
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            set -e
            cd app
            git fetch --all --tags --prune
            git checkout tags/${{ inputs.tag }}
            docker compose -f compose.yaml -f compose.prod.yaml build --pull --no-cache
            docker compose down
            SERVER_NAME=${{ secrets.SERVER_NAME }}
            APP_SECRET=${{ secrets.APP_SECRET }}
            CADDY_MERCURE_JWT_SECRET=${{ secrets.JWT_SECRET }}
            docker compose -f compose.yaml -f compose.prod.yaml up --wait
          EOF

      - name: Delete SSH
        run: rm -rf ~/.ssh/
