name: cd

on:
  workflow_dispatch:
    
jobs:
  deployment:
    name: Deploy production
    
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          
      - name: Checkout
        run: ssh production 'cd app && git pull origin main --rebase'
        
      - name: Delete SSH
        run: rm -rf ~/.ssh/
