name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Docker Lint
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  tests:
    name: Tests
    
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      -
        name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      
      -
        name: Start services
        run: >
          GITHUB_USERNAME=${{ secrets.GH_USERNAME }}
          GITHUB_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
          docker compose up --wait --no-build
          
      - name: Build assets
        run: docker compose exec -T php bin/console -e test tailwind:build
      
      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
      
      -
        name: Check HTTPS reachability
        run: curl -vk --fail-with-body https://localhost
      
      -
        name: Create test database
        if: false
        run: docker compose exec -T php bin/console -e test doctrine:database:create
      
      -
        name: Run migrations
        if: false
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      
      -
        name: Doctrine Schema Validator
        if: false
        run: docker compose exec -T php bin/console -e test doctrine:schema:validate
      
      -
        name: Run PHPUnit
        run: make coverage
