name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Docker Lint
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  tests:
    name: Tests
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
            compose.test.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        run: >
          GITHUB_USERNAME=${{ secrets.GH_USERNAME }}
          GITHUB_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
          TWITTER_USER_ID=${{ secrets.TWITTER_USER_ID }}
          TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}
          docker compose up --wait --no-build

      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost

      - name: Check HTTPS reachability
        run: curl -vk --fail-with-body https://localhost
 
      - name: Run PHP CS Fixer
        run: docker compose exec -T php vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --ansi

      - name: Run PHPStan
        run: docker compose exec -T php vendor/bin/phpstan analyse --memory-limit 256M

      - name: Create test database
        if: false # Remove this line if Doctrine ORM is installed
        run: docker compose exec -T php bin/console -e test doctrine:database:create

      - name: Run migrations
        if: false # Remove this line if Doctrine Migrations is installed
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Doctrine Schema Validator
        if: false # Remove this line if Doctrine ORM is installed
        run: docker compose exec -T php bin/console -e test doctrine:schema:validate

      - name: Run PHPUnit
        if: false
        run: docker compose exec -T php bin/phpunit
