name: ci

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Docker Lint
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  tests:
    name: Tests
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        run: >
          GITHUB_USERNAME=${{ secrets.GH_USERNAME }}
          GITHUB_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
          docker compose up --wait --no-build

      - name: Build assets
        run: make asset-build

      - name: Create test database
        run: make db-test
        
      - name: Run PHP CS Fixer
        run: make phpcsfixer-dry

      - name: Run Twig CS Fixer
        run: make twigcsfixer-dry

      - name: Run PHPStan
        run: make phpstan

      - name: Run PHPUnit
        run: make coverage
